version: "2"
services:

  #PHP Service
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/laravel
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/laravel
      - ./storage/app/public:/var/www/laravel/public/storage
    networks:
      - app-network

  #Nginx Service
  webserva:
    container_name: webserv
    image: nginx:latest
    working_dir: /var/www/laravel
    restart: unless-stopped
    ports:
      - "9081:80"
      - "4431:443"
    volumes:
      - ./:/var/www/laravel
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log/:/var/log/nginx/
    networks:
      - app-network

  #MySQL Service
  dba:
    container_name: dba
    image: wangxian/alpine-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: sipproject
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
